#lang sicp

; Exercise 1.9: Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.

; (define (+ a b)
;   (if (= a 0)
;       b
;       (inc (+ (dec a ) b))))

; (define (+ a b)
;   (if (= a 0)
;       b
;       (+ (dec a) (inc b))))
	  
; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?


; Answer:

; Case 1:
; Iterative process, linear iteration, shape straight, space complexity remains the same over time
; Iteration has all of its state in explicit variables

; (define (+ a b)
;  (if (= a 0)
;      b
;      ( inc (+ (dec a) b))))

; iterative:

; (+ 3 4)
; (+ 2 5)
; (+ 1 6)
; (+ 0 7)
; 7

; Case 2:
; Recursive process, linear recursion, shape curved, space complexity is proportional to time.
; Recursion has formal parameters for the program, as well as stuff contained in the computer for use later.

; (define (+ a b)
;   (if (= a 0)
;       b
;       (+ (dec a) (inc b))))

; recursive:

; (+ 3 4)
; (+ (+ 2 4))
; (+ (+ (+ 1 4)))
; (+ (+ (+ (+ 0 4)))
; (+ (+ (+ 4))))
; (+ (+ 5))
; (+ 6)
; 7




